"""
This type stub file was generated by pyright.
"""

from .mymemory_translated import MyMemoryProvider
from .microsoft import MicrosoftProvider
from .deepl import DeeplProvider
from .libre import LibreProvider

__all__ = ['MyMemoryProvider', 'MicrosoftProvider', 'DeeplProvider', 'LibreProvider']
