"""
This type stub file was generated by pyright.
"""

from abc import ABCMeta, abstractmethod

class BaseProvider:
    __metaclass__ = ABCMeta
    name = ...
    base_url = ...
    def __init__(self, to_lang, from_lang=..., secret_access_key=..., region=..., **kwargs) -> None:
        ...
    
    @abstractmethod
    def get_translation(self, params):
        ...
    


