"""
This type stub file was generated by pyright.
"""

from .base import BaseProvider

class DeeplProvider(BaseProvider):
    '''
    @DeeplProvider: This is a integration with DeepL Translator API.
    Website: https://www.deepl.com
    Documentation: https://www.deepl.com/docs-api
    '''
    name = ...
    base_free_url = ...
    base_pro_url = ...
    def __init__(self, **kwargs) -> None:
        ...
    
    def get_translation(self, text): # -> Any:
        ...
    


