"""
This type stub file was generated by pyright.
"""

from .base import BaseProvider

class LibreProvider(BaseProvider):
    """
    @LibreProvider: This is a integration with LibreTranslate translation API.
    Website: https://libretranslate.com/
    Documentation: https://libretranslate.com/docs/
    Github: https://github.com/LibreTranslate/LibreTranslate
    """
    name = ...
    def __init__(self, to_lang, from_lang=..., secret_access_key=..., region=..., base_url=..., **kwargs) -> None:
        ...
    
    def get_translation(self, text): # -> Any:
        ...
    


