"""
This type stub file was generated by pyright.
"""

from .providers import MyMemoryProvider

DEFAULT_PROVIDER = MyMemoryProvider
TRANSLATION_API_MAX_LENGHT = ...
PROVIDERS_CLASS = ...
class Translator:
    def __init__(self, to_lang, from_lang=..., provider=..., secret_access_key=..., region=..., **kwargs) -> None:
        ...
    
    def translate(self, text): # -> LiteralString:
        ...
    


